
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MiejsceServiceSoapService", targetNamespace = "http://SOAP/", wsdlLocation = "http://localhost:8080/Pracownikservice?wsdl")
public class MiejsceServiceSoapService
    extends Service
{

    private final static URL MIEJSCESERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MIEJSCESERVICESOAPSERVICE_EXCEPTION;
    private final static QName MIEJSCESERVICESOAPSERVICE_QNAME = new QName("http://SOAP/", "MiejsceServiceSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Pracownikservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MIEJSCESERVICESOAPSERVICE_WSDL_LOCATION = url;
        MIEJSCESERVICESOAPSERVICE_EXCEPTION = e;
    }

    public MiejsceServiceSoapService() {
        super(__getWsdlLocation(), MIEJSCESERVICESOAPSERVICE_QNAME);
    }

    public MiejsceServiceSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MIEJSCESERVICESOAPSERVICE_QNAME, features);
    }

    public MiejsceServiceSoapService(URL wsdlLocation) {
        super(wsdlLocation, MIEJSCESERVICESOAPSERVICE_QNAME);
    }

    public MiejsceServiceSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MIEJSCESERVICESOAPSERVICE_QNAME, features);
    }

    public MiejsceServiceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MiejsceServiceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MiejsceServiceSoap
     */
    @WebEndpoint(name = "MiejsceServiceSoapPort")
    public MiejsceServiceSoap getMiejsceServiceSoapPort() {
        return super.getPort(new QName("http://SOAP/", "MiejsceServiceSoapPort"), MiejsceServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MiejsceServiceSoap
     */
    @WebEndpoint(name = "MiejsceServiceSoapPort")
    public MiejsceServiceSoap getMiejsceServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOAP/", "MiejsceServiceSoapPort"), MiejsceServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MIEJSCESERVICESOAPSERVICE_EXCEPTION!= null) {
            throw MIEJSCESERVICESOAPSERVICE_EXCEPTION;
        }
        return MIEJSCESERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
